Repository Catrobat/Catroweb, pull requests merged in 2020-08, with the labels that each got.

#782 SHARE-350 Remove unused OAuth stuff
  assets/js/custom/register.js
  composer.lock
  templates/UserManagement/oauth_registration.html.twig
  templates/bundles/FOSUserBundle/Registration/check_email.html.twig
  templates/bundles/FOSUserBundle/Registration/register.html.twig
  templates/bundles/FOSUserBundle/Resetting/check_email.html.twig
  templates/bundles/FOSUserBundle/Resetting/request.html.twig
  templates/bundles/FOSUserBundle/Security/login.html.twig
  tests/behat/context/CatrowebBrowserContext.php
  tests/behat/features/web/authentication/OAuth.feature
  tests/behat/features/web/authentication/oauth.feature
  translations/catroweb.en.yml
Labels: enhancement

#787 SHARE-332 File Download Error Handling
  assets/js/custom/Program.js
  templates/Program/program.html.twig
  tests/behat/context/BrowserContext.php
  tests/behat/features/web/project-details/project_download.feature
  translations/catroweb.en.yml
Labels: bug, design

#825 Hotfix - use npm ci
  .github/workflows/code_quality.yml
  bin/checkCatroidRepositoryForNewBricks
Labels: enhancement, github_actions

#779 SHARE-255/Refactoring - Adminarea - Tools/Maintain
  src/Commands/Maintenance/CleanLogsCommand.php
  tests/behat/features/web/admin/server_maintenance.feature
  tests/phpUnit/Catrobat/Controller/RemovableMemoryTest.php
  tests/phpUnit/Commands/ArchiveLogsTest.php
  tests/phpUnit/Commands/CleanApkTest.php
  tests/phpUnit/Commands/CleanLogsTest.php
Labels: admin, enhancement

#835 Hotfix dev container checks
  .github/workflows/tests.yml
Labels: bug
