Repository Catrobat/Catroweb, pull requests merged in 2020-06, with the labels that each got.

#542 SHARE-251 Refactoring - Adminarea - Users | Users
  config/services.yaml
  src/Admin/UserAdmin.php
  src/Catrobat/Services/TestEnv/DataFixtures/UserDataFixtures.php
  src/Entity/User.php
  tests/behat/context/CatrowebBrowserContext.php
  tests/behat/context/DataFixturesContext.php
  tests/behat/features/admin/all_projects.feature
  tests/behat/features/admin/broadcast_notification.feature
  tests/behat/features/admin/users_users.feature
Labels: admin

#548 SHARE-258 Refactoring - Adminarea - Tools | Notifications
  src/Admin/NotificationAdmin.php
  src/Catrobat/Controller/Api/ReportController.php
  src/Entity/Notification.php
  src/Entity/UserManager.php
  tests/behat/context/CatrowebBrowserContext.php
  tests/behat/features/admin/report_notification.feature
Labels: admin

#543 SHARE-35 Status Codes Misleading
  src/Api/MediaLibraryApi.php
  src/Api/ProjectsApi.php
  src/Api/UserApi.php
  src/Catrobat/Controller/Api/MediaPackageController.php
  src/Catrobat/Controller/Api/ReportController.php
  src/Catrobat/Controller/Api/SecurityController.php
  src/Catrobat/Controller/Api/UploadController.php
  src/Catrobat/Controller/Web/CommentsController.php
  src/Catrobat/Controller/Web/ProfileController.php
  src/Catrobat/Controller/Web/ProgramController.php
  src/Catrobat/Listeners/NameValidator.php
  src/Catrobat/Listeners/VersionValidator.php
  src/Catrobat/Services/OAuthService.php
  src/Catrobat/StatusCode.php
  templates/Program/program.html.twig
  templates/UserManagement/Profile/myProfile.html.twig
Labels: enhancement

#582 SHARE-308 Refresh project dir hash on uploads
  src/Api/MediaLibraryApi.php
  src/Api/ProjectsApi.php
  src/Api/UserApi.php
  src/Catrobat/Services/ExtractedCatrobatFile.php
  src/Catrobat/Services/ExtractedFileRepository.php
  src/Catrobat/Services/ScreenshotRepository.php
  src/Catrobat/Services/TestEnv/DataFixtures/ProjectDataFixtures.php
  src/Catrobat/Services/TestEnv/DataFixtures/UserDataFixtures.php
  src/Commands/Reset/ClearExtractedProjects.php
  src/Entity/Program.php
  src/Entity/ProgramManager.php
  src/Utils/Utils.php
  symfony.lock
  tests/behat/context/ApiContext.php
  tests/behat/context/CatrowebBrowserContext.php
  tests/phpUnit/CatrobatCodeParserTests/ParsedObjectGroupTest.php
  tests/phpUnit/CatrobatCodeParserTests/ParsedObjectTest.php
  tests/phpUnit/Commands/ClearExtractedProjectsTest.php
  tests/phpUnit/Entity/ProgramManagerTest.php
  tests/phpUnit/Hook/RefreshTestEnvHook.php
Labels: bug

#595 Update ReadMe.md
  README.md
Labels: no auto-deploy

#540 SHARE-244 Refactoring - Adminarea - Featured Urls
  config/packages/security.yaml
  config/packages/sonata_admin.yaml
  config/services.yaml
  src/Admin/FeaturedProgramAdmin.php
  src/Admin/FeaturedUrlAdmin.php
  tests/behat/context/CatrowebBrowserContext.php
  tests/behat/features/admin/featured_programs.feature
  tests/behat/features/web/general/homepage.feature
Labels: admin

#688 Fix apk sql cleanup error
  src/Commands/Maintenance/CleanOldApkCommand.php
Labels: no auto-deploy
