Repository Catrobat/Catroweb, pull requests merged in 2020-12, with the labels that each got.

#1086 SHARE-413 - HOTFIX API MAIL
  src/Api/UserApi.php
  tests/behat/context/ApiContext.php
  tests/behat/features/api/user/get_logged_in_user.feature
Labels: Manual work required, can be merged

#1135 SHARE-410 Minor design fix (termsOfUse)
  assets/css/base/_brain.scss
  assets/css/custom/multi_column_article.scss
  templates/PrivacyAndTerms/licenseToPlay.html.twig
  templates/PrivacyAndTerms/termsOfUse.html.twig
Labels: design

#818 SHARE-341/CAPI_Entities_Inconsistency
  composer.json
  composer.lock
  src/Api/AuthenticationApi.php
  src/Api/MediaLibraryApi.php
  src/Api/ProjectsApi.php
  src/Entity/MediaPackageCategory.php
  templates/MediaLibrary/mediapackageindex.html.twig
  tests/behat/features/api/mediapackage/mediafile_all_get.feature
  tests/behat/features/api/mediapackage/mediafile_id_get.feature
  tests/behat/features/api/mediapackage/mediafile_search_get.feature
  tests/behat/features/api/mediapackage/mediapackage_packagename_get.feature
  tests/behat/features/web/media-library/mediapackage.feature
  tests/phpUnit/Api/MediaPackage/MediaFileAllGetTest.php
  tests/phpUnit/Api/MediaPackage/MediaFileIdGetTest.php
  tests/phpUnit/Api/MediaPackage/MediaFileSearchGetTest.php
  tests/phpUnit/Api/MediaPackage/MediaPackageNameGetTest.php
Labels: api, dependencies, php

#761 SHARE-352 API - PUT /user
  composer.json
  composer.lock
  src/Api/UserApi.php
  tests/behat/context/DataFixturesContext.php
  tests/behat/features/api/user/delete_user.feature
  tests/behat/features/api/user/update_user.feature
  tests/behat/features/api/user/user_register.feature
  tests/phpUnit/Api/User/UpdateUserTest.php
  tests/phpUnit/Api/User/UserRegisterTest.php
  translations/catroweb.en.yml
Labels: api

#1156 Hotfix: adapt to new xdebug version
  docker/Dockerfile
Labels: bug

#1122 SHARE-126 Add translation capability to project and comments via link to google translation
  .github/workflows/tests.yml
  assets/js/custom/Translation.js
  behat.yml.dist
  src/Catrobat/Services/TestEnv/DataFixtures/ProjectDataFixtures.php
  templates/Program/program.html.twig
  templates/Program/programComments.html.twig
  tests/behat/features/web/translation/translate_comments.feature
  tests/behat/features/web/translation/translate_project.feature
Labels: design, feature, po-review needed
