Repository Catrobat/Catroweb, pull requests merged in 2020-09, with the labels that each got.

#829 SHARE-343 Serve .webp images
  .gitignore
  composer.json
  composer.lock
  docker/Dockerfile
  docker/apache/catroweb.conf
  public/webp-on-demand.php
  symfony.lock
Labels: enhancement, gsoc

#883 SHARE-234 - Finish GitHub Action documentation
  .github/codecov.yml
  .github/contributing.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/check_for_new_bricks.yml
  .github/workflows/code_quality.yml
  .github/workflows/container_tests.yml
  .github/workflows/deploy.yml
  .github/workflows/sync_crowdin.yml
  .github/workflows/tests.yml
  README.md
  bin/checkCatroidRepositoryForNewBricks
  crowdin.yml
Labels: github_actions

#760 Api php unit tests
  .github/workflows/tests.yml
  tests/phpUnit/Api/MediaLibraryApiTest.php
  tests/phpUnit/Api/MediaPackage/MediaFileAllGetTest.php
  tests/phpUnit/Api/MediaPackage/MediaFileIdGetTest.php
  tests/phpUnit/Api/MediaPackage/MediaFileSearchGetTest.php
  tests/phpUnit/Api/MediaPackage/MediaPackageNameGetTest.php
  tests/phpUnit/Api/Projects/GetExampleTest.php
  tests/phpUnit/Api/Projects/GetFeaturedTest.php
  tests/phpUnit/Api/Projects/GetLoggedInUserTest.php
  tests/phpUnit/Api/Projects/GetMostDownloadedTest.php
  tests/phpUnit/Api/Projects/GetMostViewedTest.php
  tests/phpUnit/Api/Projects/GetProjectTest.php
  tests/phpUnit/Api/Projects/GetPublicUserTest.php
  tests/phpUnit/Api/Projects/GetRandomTest.php
  tests/phpUnit/Api/Projects/GetRecentTest.php
  tests/phpUnit/Api/Projects/GetScratchRemixTest.php
  tests/phpUnit/Api/Projects/GetSearchTest.php
  tests/phpUnit/Api/User/DeleteUserTest.php
  tests/phpUnit/Api/User/GetPrivateUserTest.php
  tests/phpUnit/Api/User/GetPublicUserTest.php
  tests/phpUnit/Api/User/UpdateUserTest.php
  tests/phpUnit/Api/User/UserRegisterTest.php
  tests/phpUnit/Api/User/UsersSearchTest.php
  tests/phpUnit/Commands/ClearCompressedProjectsTest.php
  tests/phpUnit/Hook/RefreshTestEnvHook.php
Labels: gsoc

#855 SHARE-310 New OAuth API
  .env
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  src/Api/AuthenticationApi.php
  src/Api/ProjectsApi.php
  symfony.lock
  tests/behat/features/api/authentication/oauth_login.feature
Labels: gsoc
